version: "3.9"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql

  api:
    build: .
    container_name: employeeapi
    depends_on:
      - mssql
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Default=Server=mssql,1433;Database=EmployeeDb;User Id=sa;Password=Admin@123$;TrustServerCertificate=True
      - Jwt__Issuer=EmployeeApi
      - Jwt__Audience=EmployeeApiClient
      - Jwt__Key=SuperSecretKey_ChangeMe_AtLeast32Chars_Long
volumes:
  mssqldata:
